### Send Request for all credentials

GET http://localhost:3000/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}

### Send Request for single credential

GET http://localhost:3000/api/credentials/TestService
Authorization: {{$dotenv MASTERPASSWORD}}

### Add new credential

POST http://localhost:3000/api/credentials
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "TestService",
    "userName": "PF",
    "password": "PW"
}

### Update credential

PATCH  http://localhost:3000/api/credentials/Firefox
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "Firefox",
    "userName": "Patrick",
    "password": "NewPassword"
}

### Delete credential
DELETE http://localhost:3000/api/credentials/YouTube
Content-Type: application/json