### Send Request for all credentials

GET http://localhost:3000/api/credentials

### Send Request for single credential

GET http://localhost:3000/api/credentials/YouTube
Authorization: {{$dotenv MASTERPASSWORD}}

### Add new credential

POST http://localhost:3000/api/credentials
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "YouTube",
    "userName": "Patrick",
    "password": "DefaultPassword"
}

### Update credential

PUT http://localhost:3000/api/credentials/Google
Content-Type: application/json

{
    "service": "YouTube",
    "userName": "Patrick",
    "password": "DefaultPassword"
}

### Delete credential
DELETE http://localhost:3000/api/credentials/YouTube
Content-Type: application/json